import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "./Provider"
import { ClerkProvider } from "@clerk/nextjs";
import { Taviraj } from 'next/font/google'
import { Mali } from 'next/font/google'


const taviraj = Taviraj({
  weight:'400',
  subsets:['latin', 'thai']
})

const mali = Mali({
  weight:'400',
  subsets:['latin', 'thai']
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${taviraj.className}`}
        >
        <Provider>

          <Navbar />

          <main className="container items-center ">
          {children}
          </main>

        </Provider>
      </body>
    </html>
        </ClerkProvider>
  );
}
